<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Product Orders Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 11px;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #6366f1;
        }
        .header h1 {
            margin: 0;
            color: #6366f1;
            font-size: 22px;
        }
        .header p {
            margin: 5px 0 0;
            color: #666;
            font-size: 12px;
        }
        .meta {
            display: flex;
            justify-content: space-between;
            margin-bottom: 15px;
            font-size: 11px;
            color: #666;
        }
        .meta-item {
            display: inline-block;
            margin-right: 30px;
        }
        .meta-label {
            font-weight: bold;
            color: #333;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th {
            background-color: #6366f1;
            color: white;
            padding: 10px 8px;
            text-align: left;
            font-weight: 600;
            font-size: 10px;
            text-transform: uppercase;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #e5e7eb;
            font-size: 10px;
        }
        tr:nth-child(even) {
            background-color: #f9fafb;
        }
        tr:hover {
            background-color: #f3f4f6;
        }
        .status {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 9px;
            font-weight: 600;
        }
        .status-pending_payment { background: #fef3c7; color: #92400e; }
        .status-processing { background: #dbeafe; color: #1e40af; }
        .status-completed { background: #d1fae5; color: #065f46; }
        .status-cancelled { background: #fee2e2; color: #991b1b; }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 9px;
            color: #999;
            border-top: 1px solid #e5e7eb;
            padding-top: 10px;
        }
        .no-data {
            text-align: center;
            padding: 40px;
            color: #999;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $product->name }} - Orders Report</h1>
        <p>Period: {{ $period }}</p>
    </div>

    <div class="meta">
        <span class="meta-item"><span class="meta-label">Product:</span> {{ $product->name }}</span>
        <span class="meta-item"><span class="meta-label">Price:</span> RM {{ number_format($product->price, 2) }}</span>
        <span class="meta-item"><span class="meta-label">Generated:</span> {{ $generatedAt }}</span>
    </div>

    @if(count($data) > 0)
        <table>
            <thead>
                <tr>
                    <th>Order #</th>
                    <th>Date</th>
                    <th>Customer</th>
                    <th>Phone</th>
                    <th>Qty</th>
                    <th>Unit Price</th>
                    <th>Subtotal</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $row)
                    <tr>
                        <td>{{ $row['Order ID'] }}</td>
                        <td>{{ $row['Order Date'] }}</td>
                        <td>{{ $row['Customer Name'] }}</td>
                        <td>{{ $row['Customer Phone'] }}</td>
                        <td>{{ $row['Quantity'] }}</td>
                        <td>RM {{ $row['Unit Price (RM)'] }}</td>
                        <td>RM {{ $row['Subtotal (RM)'] }}</td>
                        <td>
                            @php
                                $statusClass = 'status-' . strtolower(str_replace(' ', '_', $row['Order Status']));
                            @endphp
                            <span class="status {{ $statusClass }}">{{ $row['Order Status'] }}</span>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">
            <p>No orders found for this period.</p>
        </div>
    @endif

    <div class="footer">
        Generated by JanjiChat &bull; {{ $generatedAt }}
    </div>
</body>
</html>
